research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is {current_year}.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst

lead_qualification_task:
  description: >
    Phân tích đoạn hội thoại trao đổi với lead customer và đưa ra đánh giá về khả năng 
    chuyển đổi thành khách hàng. Xác định các yêu cầu, ngân sách, thẩm quyền quyết định 
    và thời gian triển khai để xác định lead có đủ điều kiện (qualified) hay không.
    Đoạn script giao tiếp: {conversation_transcript}
  expected_output: >
    Báo cáo phân tích chi tiết bao gồm: đánh giá về nhu cầu, ngân sách, thẩm quyền quyết định,
    thời gian triển khai, điểm số đánh giá, kết luận (qualified/not qualified) và đề xuất hành động tiếp theo.
  agent: lead_qualifier
